##GO Enrichment Analysis R Code
```{r init_go_kegg}
de_file <- "DESeq2.OA.vs.Norm.DE"
org_db <- "org.Hs.eg.db"
```
##It's better to be a gene name in the entrez format.
```{r}
de<-read.table(paste0(de_file,".symbol.txt"), sep="\t", comment="", quote="",stringsAsFactors = F)
colnames(de) <- c('gene', 'samp')
library(org.Hs.eg.db)
cols <- c("ENTREZID")
s<-select(org.Hs.eg.db, keys=de$gene, columns=cols, keytype="SYMBOL")
s<-na.omit(s)
s<-s[!duplicated(s[,1]),]
de<-merge(de,s,by.x="gene",by.y="SYMBOL")
de<-data.frame(de$ENTREZID,de$samp)
write.table(de,paste0(de_file,".Entrez.txt"),col.names = F,row.names = F,sep = "\t",quote=F)
```
```{r}
library("clusterProfiler")
library(ggplot2)
```
```{r}
data <- read.table(paste0(de_file,".Entrez.txt"), sep="\t", comment="", quote="")
colnames(data) <- c('gene', 'samp')
sampC <- unique(data$samp)
```
```{r}
kk<-list()
for(samp in sampC) {
	id <- unique(data[data$samp==samp, 1])
	kk[[samp]] <- enrichGO(gene = id,
                 OrgDb = org.Hs.eg.db,
                 pvalueCutoff =0.05,
                 qvalueCutoff = 0.2,
                 ont="ALL",
                 readable =T)
}
save(kk,file="GO.Rdata")
result <- list()
for(samp in sampC) {
	result[[samp]] <- data.frame(kk[[samp]])
	result[[samp]]$Group <- samp
}
result <- do.call(rbind, result)
output <- paste0(de_file, ".GO.txt")
write.table(result, file=output, quote=F,sep="\t",row.names=F,col.names=T)
summary(result)
result_s<-data.frame()
for(samp in sampC){
  tmp<-data.frame(result[result$Group==samp,])
  tmp<-tmp[order(tmp$qvalue),]
  if(nrow(tmp)>10)  tmp<-tmp[1:10,]
  result_s<-rbind(result_s,tmp)
}

output <- paste0(de_file, ".GO.top10.txt")
write.table(result_s, file=output, quote=F,sep="\t",row.names=F,col.names=T)

```
```{r}
library(plyr)
library(stringr)
library(ggplot2)
library(grid)

options(scipen=999)

numCheck <- function(x){
  x <- sapply(x, as.character)
  is.integer  <- grepl("^-?\\d+$", x)
  is.fraction <- grepl("^-?\\d+\\/\\d+$", x)
  is.float <- grepl("^-?\\d+\\.\\d+$", x)
  is.percent <- grepl("[0-9.]+%$", x)
  is.mixed    <- grepl("^-?\\d+ \\d+\\/\\d+$", x)
  return(all(is.integer | is.fraction | is.float | is.mixed | is.percent))
}

mixedToFloat <- function(x){
  x <- sapply(x, as.character)
  is.integer  <- grepl("^-?\\d+$", x)
  is.fraction <- grepl("^-?\\d+\\/\\d+$", x)
  is.float <- grepl("^-?\\d+\\.\\d+$", x)
  is.mixed    <- grepl("^-?\\d+ \\d+\\/\\d+$", x)
  is.percent <- grepl("[0-9.]+%$", x)
  stopifnot(all(is.integer | is.fraction | is.float | is.mixed | is.percent))

  numbers <- strsplit(x, "[ /%]")

  ifelse(is.integer,  as.numeric(sapply(numbers, `[`, 1)),
         ifelse(is.percent,  as.numeric(sapply(numbers, `[`, 1))/100,
                ifelse(is.float,    as.numeric(sapply(numbers, `[`, 1)),
                       ifelse(is.fraction, 
                              as.numeric(sapply(numbers, `[`, 1)) /
                                as.numeric(sapply(numbers, `[`, 2)),
                              as.numeric(sapply(numbers, `[`, 1)) +
                                as.numeric(sapply(numbers, `[`, 2)) /
                                as.numeric(sapply(numbers, `[`, 3))))))
  
}

output <- paste0(de_file, ".GO.top10.txt")
result<-read.table(output,sep = "\t",header = T)

data <- result

data$Group<-factor(data$Group,levels = unique(data$Group),labels = c("Up","Down"))

if (numCheck(data$GeneRatio)) {
	xval_type = "numeric"
}

if (xval_type != "string"){
	if (numCheck(data$GeneRatio)) {
		data$GeneRatio = mixedToFloat(data$GeneRatio)
	}
}

log_name = paste0("negLog10_", "qvalue")
col_name_data <- colnames(data)
col_name_data <- c(col_name_data, log_name)
if (! numCheck(data$qvalue)) {
	stop("**qvalue** column is <strong>not</strong> <mark>numerical</mark> column. Plase do <strong>not</strong> set log10 transform on this column.\n")}else {
		data$qvalue = mixedToFloat(data$qvalue)
	}
data$log_name <- log10(data$qvalue) * (-1)
data$log_name[data$log_name==Inf] =
	 max(data$log_name[data$log_name!=Inf]) + 2
data$log_name[data$log_name>quantile(data$log_name,0.75)] =
	 quantile(data$log_name,0.75)
colnames(data) <- col_name_data

if (! numCheck(data$negLog10_qvalue)) {
	stop("<strong>Color</strong> variable must be <mark>numbers</mark>.")
}


colnames(data)<-col_name_data
data$negLog10_qvalue = mixedToFloat(data$negLog10_qvalue)

# Get the count of each unique Term
data_freq <- as.data.frame(table(data$Description))
#IDctct frequences of replication
colnames(data_freq) <- c("Description", "IDctct")
data2 <- merge(data, data_freq, by="Description")
# Collapse sample for each Term
data_samp <- ddply(data2, "Description", summarize,
                   sam_ct_ct_ct=paste(Group, collapse="_"))#
data2 <- merge(data2, data_samp, by="Description")
#print(data2)
data2$Group<-factor(data2$Group,levels = rev(levels(data$Group)))

if (xval_type != "string"){
  data3 <- data2[order(data2$IDctct, data2$sam_ct_ct_ct,data2$Group, data2$GeneRatio, data2$negLog10_qvalue), ]
	} else {
		data3 <- data2[order(data2$IDctct, data2$sam_ct_ct_ct, data2$Group, data2$negLog10_qvalue), ]
	}

term_order <- unique(data3$Description)
data$Description <- factor(data$Description, levels=term_order, ordered=T)

color_v <- c("blue", "red")
legend_pos_par="right"
p<-list()
for (i in levels(data$Group)) {
  if(i==levels(data$Group)[1]) shape=24 else shape=25
  data_s<-data[data$Group==i,]
  p[[i]] <-ggplot(data_s, aes(x=GeneRatio,y=Description)) + 
  labs(x="", y="") + 
  #labs(title="Significant pathways of GO enrichment analysis")
	geom_point(aes(size=Count,color=negLog10_qvalue,fill=negLog10_qvalue),shape=shape)+ 	
	scale_color_gradient(low=color_v[1], 
	                     high=color_v[2],
	                     name=expression(paste("- Log"[10],"(q)")))+
  scale_fill_gradient(low=color_v[1], 
	                     high=color_v[2],
                      guide = F)+
  scale_size_continuous(breaks  = c(min(data_s$Count),round(median(data_s$Count)),max(data_s$Count)))+
  scale_shape_manual(values = shape)+
  guides(color=guide_colorbar(order = 1),size=guide_legend(order = 0,reverse = T))+
  theme_bw()+
  theme(legend.position=legend_pos_par)+
  theme(panel.border = element_rect(),panel.grid = element_blank())+
  xlab("GeneRatio")+
  facet_grid(ONTOLOGY~.,scales = "free")
}
```
## KEGG Enrichment Analysis
```{r init_go_kegg}
suppressMessages(library(org_db, character.only = T))
suppressMessages(library(DOSE))
library(clusterProfiler)
```
```{r}
de_file <- "DESeq2.OA.vs.Norm.DE"
org_db <- "org.Hs.eg.db"
```

```{r, echo=T}
data <- read.table(paste0(de_file,".Entrez.txt"), sep="\t", comment="", quote="")
colnames(data) <- c('gene', 'samp')
sampC <- unique(data$samp)
```
```{r}
result <- list()
kk<-list()
for(samp in sampC) {
	id <- unique(data[data$samp==samp, 1])
	print(paste0("KEGG enrichment for ", samp))
	kk[[samp]] <- enrichKEGG(id,
	                         organism="hsa",
	                         keyType='kegg',
	                         pvalueCutoff=0.05,
	                         pAdjustMethod="BH", 
	                         qvalueCutoff=0.2)
	result[[samp]] <- as.data.frame(setReadable(kk[[samp]], "org.Hs.eg.db", keyType="ENTREZID"))
	result[[samp]]$Group <- samp
}

result <- do.call(rbind, result)
output <- paste0(de_file, ".KEGG.txt")
write.table(result, file=output, quote=F,sep="\t",row.names=F,col.names=T)
summary(result)

result_s<-data.frame()
for(samp in sampC){
  tmp<-data.frame(result[result$Group==samp,])
  tmp<-tmp[order(tmp$qvalue),]
  if(nrow(tmp)>10)  tmp<-tmp[1:10,]
  result_s<-rbind(result_s,tmp)
}

output <- paste0(de_file, ".KEGG.top10.txt")
write.table(result_s, file=output, quote=F,sep="\t",row.names=F,col.names=T)

save(kk,file="KEGG.Rdata")
```
## Enrichment Analysis Bubble Chart Drawing

```{r}
library(plyr)
library(stringr)
library(ggplot2)
library(grid)

options(scipen=999)

numCheck <- function(x){
  x <- sapply(x, as.character)
  is.integer  <- grepl("^-?\\d+$", x)
  is.fraction <- grepl("^-?\\d+\\/\\d+$", x)
  is.float <- grepl("^-?\\d+\\.\\d+$", x)
  is.percent <- grepl("[0-9.]+%$", x)
  is.mixed    <- grepl("^-?\\d+ \\d+\\/\\d+$", x)
  return(all(is.integer | is.fraction | is.float | is.mixed | is.percent))
}

mixedToFloat <- function(x){
  x <- sapply(x, as.character)
  is.integer  <- grepl("^-?\\d+$", x)
  is.fraction <- grepl("^-?\\d+\\/\\d+$", x)
  is.float <- grepl("^-?\\d+\\.\\d+$", x)
  is.mixed    <- grepl("^-?\\d+ \\d+\\/\\d+$", x)
  is.percent <- grepl("[0-9.]+%$", x)
  stopifnot(all(is.integer | is.fraction | is.float | is.mixed | is.percent))

  numbers <- strsplit(x, "[ /%]")

  ifelse(is.integer,  as.numeric(sapply(numbers, `[`, 1)),
         ifelse(is.percent,  as.numeric(sapply(numbers, `[`, 1))/100,
                ifelse(is.float,    as.numeric(sapply(numbers, `[`, 1)),
                       ifelse(is.fraction, 
                              as.numeric(sapply(numbers, `[`, 1)) /
                                as.numeric(sapply(numbers, `[`, 2)),
                              as.numeric(sapply(numbers, `[`, 1)) +
                                as.numeric(sapply(numbers, `[`, 2)) /
                                as.numeric(sapply(numbers, `[`, 3))))))
  
}
output <- paste0(de_file, ".KEGG.top10.txt")
result<-read.table(output,sep = "\t",header = T)

data <- result

data$Group<-factor(data$Group,levels = unique(data$Group),labels = c("Up","Down"))

if (numCheck(data$GeneRatio)) {
	xval_type = "numeric"
}

if (xval_type != "string"){
	if (numCheck(data$GeneRatio)) {
		data$GeneRatio = mixedToFloat(data$GeneRatio)
	}
}

log_name = paste0("negLog10_", "qvalue")
col_name_data <- colnames(data)
col_name_data <- c(col_name_data, log_name)
if (! numCheck(data$qvalue)) {
	stop("**qvalue** column is <strong>not</strong> <mark>numerical</mark> column. Plase do <strong>not</strong> set log10 transform on this column.\n")}else {
		data$qvalue = mixedToFloat(data$qvalue)
	}
data$log_name <- log10(data$qvalue) * (-1)
data$log_name[data$log_name==Inf] =
	 max(data$log_name[data$log_name!=Inf]) + 2
data$log_name[data$log_name>quantile(data$log_name,0.75)] =
	 quantile(data$log_name,0.75)
colnames(data) <- col_name_data

if (! numCheck(data$negLog10_qvalue)) {
	stop("<strong>Color</strong> variable must be <mark>numbers</mark>.")
}

colnames(data)<-col_name_data
data$negLog10_qvalue = mixedToFloat(data$negLog10_qvalue)

# Get the count of each unique Term
data_freq <- as.data.frame(table(data$Description))
#IDctct frequences of replication
colnames(data_freq) <- c("Description", "IDctct")
data2 <- merge(data, data_freq, by="Description")
# Collapse sample for each Term

data_samp <- ddply(data2, "Description", summarize,
                   sam_ct_ct_ct=paste(Group, collapse="_"))#
data2 <- merge(data2, data_samp, by="Description")
#print(data2)
data2$Group<-factor(data2$Group,levels = rev(levels(data$Group)))

if (xval_type != "string"){
  data3 <- data2[order(data2$IDctct, data2$sam_ct_ct_ct,data2$Group, data2$GeneRatio, data2$negLog10_qvalue), ]
	} else {
		data3 <- data2[order(data2$IDctct, data2$sam_ct_ct_ct, data2$Group, data2$negLog10_qvalue), ]
	}

term_order <- unique(data3$Description)
data$Description <- factor(data$Description, levels=term_order, ordered=T)

color_v <- c("blue", "red")
legend_pos_par="right"
p<-list()
for (i in levels(data$Group)) {
  if(i==levels(data$Group)[1]) shape=24 else shape=25
  data_s<-data[data$Group==i,]
  p[[i]] <-ggplot(data_s, aes(x=GeneRatio,y=Description)) + 
  labs(x="", y="") + 
  #labs(title="Significant pathways of KEGG enrichment analysis")
	geom_point(aes(size=Count,color=negLog10_qvalue,fill=negLog10_qvalue),shape=shape)+ 	
	scale_color_gradient(low=color_v[1], 
	                     high=color_v[2],
	                     name=expression(paste("- Log"[10],"(q)")))+
  scale_fill_gradient(low=color_v[1], 
	                     high=color_v[2],
                      guide = F)+
  scale_size_continuous(breaks  = c(min(data_s$Count),round(median(data_s$Count)),max(data_s$Count)))+
  scale_shape_manual(values = shape)+
  guides(color=guide_colorbar(order = 1),size=guide_legend(order = 0,reverse = T))+
  theme_classic()+
  theme(legend.position=legend_pos_par)+
  xlab("GeneRatio")
}
```
